spring:
  application:
    name: billing-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  datasource:
    url: ${dbUrl}
    username: ${dbUser}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}:8761/eureka
